name: Release
on: [push, pull_request]
jobs:
  release_pypi:
    name: Release to Pypi
    runs-on: ubuntu-18.04
    needs: build_wheels

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Retrieve wheels
        uses: actions/download-artifact@v2
        with:
          path: ./dist/*
      - name: list files
        run: list ./dist/
