name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-11]

    steps:
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: install poetry
        run: pip install -U pip poetry pytest

      - name: build
        run: poetry build

      - name: install the built wheel
        run: "pip install ./dist/*.whl"

      - name: run tests
        run: pytest tests

      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*
